config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  #signup routes
  get "/signup", to: "users#new"
  get "/profile", to: "users#show"
  resources :users, except: [:new, :show], path: "/profile" do 
    resources :posts, exept: [:index]
  end

  #session routes
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  resources :sessions, only: [:create]
  #other shit

  resources :cities, only: [:show], param: :short_name

end

#         Prefix Verb   URI Pattern                              Controller#Action
#           root GET    /                                        home#index
#         signup GET    /signup(.:format)                        users#new
#        profile GET    /profile(.:format)                       users#show
#     user_posts GET    /users/:user_id/posts(.:format)          posts#index {:exept=>[:index]}
#                POST   /users/:user_id/posts(.:format)          posts#create {:exept=>[:index]}
#  new_user_post GET    /users/:user_id/posts/new(.:format)      posts#new {:exept=>[:index]}
# edit_user_post GET    /users/:user_id/posts/:id/edit(.:format) posts#edit {:exept=>[:index]}
#      user_post GET    /users/:user_id/posts/:id(.:format)      posts#show {:exept=>[:index]}
#                PATCH  /users/:user_id/posts/:id(.:format)      posts#update {:exept=>[:index]}
#                PUT    /users/:user_id/posts/:id(.:format)      posts#update {:exept=>[:index]}
#                DELETE /users/:user_id/posts/:id(.:format)      posts#destroy {:exept=>[:index]}
#          users GET    /users(.:format)                         users#index
#                POST   /users(.:format)                         users#create
#      edit_user GET    /users/:id/edit(.:format)                users#edit
#           user PATCH  /users/:id(.:format)                     users#update
#                PUT    /users/:id(.:format)                     users#update
#                DELETE /users/:id(.:format)                     users#destroy
#          login GET    /login(.:format)                         sessions#new
#         logout GET    /logout(.:format)                        sessions#destroy
#       sessions POST   /sessions(.:format)                      sessions#create
#           city GET    /cities/:short_name(.:format)            cities#show

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :posts, dependent: :destroy

	validates :email, :presence => true, uniqueness: true
	validates :username, :presence => true, uniqueness: true
	validates :password, :presence => true, confirmation: true
	# validates :password_confirmation, presence: true

	has_attached_file :avatar,
	:styles => { :medium => "150x150>" },
	:path => "avatars/:id/:style/avatar.:extension",
	:default_url => "/profile-placeholder.jpg",
	:storage => :s3,
    :s3_credentials => Proc.new { |a| a.instance.s3_credentials },
    :s3_host_name => 's3-us-west-1.amazonaws.com'

    def s3_credentials
	 { :bucket => ENV['S3_BUCKET'], :access_key_id => ENV['S3_PUBLIC_KEY'], :secret_access_key => ENV['S3_SECRET'] }
	end

	validates_attachment :avatar,
	:content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] },
	:size => { :in => 0..10000.kilobytes }

	extend FriendlyId
	friendly_id :username, use: [:slugged, :finders]

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #form to create new user
  def new
    if current_user
      redirect_to profile_path
    else
      @user = User.new
      render :new
    end
  end

  #create new user in db
  def create
    if current_user
      redirect_to profile_path
    else
  	  @user = User.new(user_params)
  	  if @user.save
  		  session[:user_id] = @user.id
  		  redirect_to profile_path
        flash[:notice] = "Complete your profile!"
  	  else
  		  redirect_to signup_path
  	  end
    end
  end

  #update the profile page
  def update
    if current_user
      #get updated data
      updated_attributes = params.require(:user).permit(:username, :first_name, :last_name, :current_city)
      # update the creature
      current_user.update_attributes(updated_attributes)
      redirect_to profile_path
    else
      redirect_to root_path
    end
  end

  #show profile page
  def show
    @user = current_user
    @posts = @user.posts
    session[:return_to] = profile_path
    
  	render :show
  end

  #private methods
  private
  	def user_params
  		params.require(:user).permit(:avatar, :username, :first_name, :last_name, :password, :password_confirmation, :email, :current_city)
  	end
end

app/helpers/users_helper.rb
module UsersHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end

end

app/views/users/_showposts.html.erb
<% @posts.each do |p| %>

<div class="post-border">

	<div class="dropdown pull-right">
		<button class="glyphicon glyphicon-chevron-down dropdown-toggle button" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
		</button>
		<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
			<li><a href="#"><%= link_to "Profile", profile_path(@user) %></a></li>
			<li><a href="#"><%= link_to "Edit Post", edit_user_post_path(@user, p) %></a></li>
			<li><a href="#"><%= link_to "Show Post", user_post_path(@user, p) %></a></li>
			<li><a href="#"><%= link_to "Delete Post", user_post_path(@user, p), method: :delete, data: {confirm: "Are you sure?"} %></a></li>
		</ul>
	</div>
	<%= image_tag p.photo.url(:medium) %>
	<h3 class="title-border">
		<%= p.title %><span class="author-post"> by <%= User.find(p.user_id).username %></span><br>
	</h3>
	<hr class="style-one">
	<%= City.find(p.city_id).city_name %><br>
	<%= p.body %><br>
</div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 post animated slideInLeft">
    <h1>Edit Your Profile Information</h1>
    <hr>
    <%= form_for current_user do |f| %>
      

      <div class="form-group">
        <%= f.text_field :first_name, placeholder: "First Name", autofocus: true, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.text_field :current_city, placeholder: "Current City", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.text_field :username, placeholder: "Username", class: "form-control" %>
      </div>
      <%= f.submit "Submit", class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 post animated slideInUp">
    <h1>Sign Up</h1>
    <hr>
    
    <%= flash_messages %>

    <%= form_for @user, :validate => true, :url => users_path, :html => { :multipart => true } do |f| %>
      <div class="form-group">
        <%= f.email_field :email, placeholder: "Email", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.text_field :username, placeholder: "Username", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.password_field :password_confirmation, placeholder: "Password Confirmation", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.file_field :avatar %>
      </div>
      <%= f.submit "Sign Up", class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div id="masthead">  
  <div class="container">
    <div class="row">
      <div class="col-md-12 profile">
        <h3 class="animated slideInLeft"><%= current_user.username %><%= "'s " %>Posts</h3>
        <div class="col-md-8 animated slideInUp">
          <%= render 'users/showposts' %>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-3 profile-section text-center animated slideInRight">
          <div class="dropdown pull-left">
            <button class="glyphicon glyphicon-chevron-down dropdown-toggle button" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to "Update Profile", edit_user_path(@user) %></li>
            </ul>
          </div>
          <div class="profile-img img-responsive center-block" alt="Responsive image">
            <%= image_tag @user.avatar.url(:medium), class: "img-circle" %>
          </div>
            <h1><%= current_user.first_name %><%= " " %> <%= current_user.last_name %><span>
              <hr class="style-one">
              <p class="profile-body"><%= current_user.current_city %></p>
              <p class="profile-body">Joined Since: 
                <%= current_user.created_at.strftime("%b. %Y") %>
              </p>
            </h1>
        </div>
      </div>  
    </div> 
  </div>
  

app/views/users/update.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Edit Your Profile Information</h1>
    <hr>
    <%= form_for @user do |f| %>
      

      <div class="form-group">
        <%= f.text_field :first_name, placeholder: "First Name", autofocus: true, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.text_field :current_city, placeholder: "Current City", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.email_field :email, placeholder: "Email", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.text_field :username, placeholder: "Username", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
      </div>
      <%= f.submit "Submit", class: "btn btn-default" %>
    <% end %>
  </div>
</div>