config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  #signup routes
  get "/signup", to: "users#new"
  get "/profile", to: "users#show"
  resources :users, except: [:new, :show], path: "/profile" do 
    resources :posts, exept: [:index]
  end

  #session routes
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  resources :sessions, only: [:create]
  #other shit

  resources :cities, only: [:show], param: :short_name

end

#         Prefix Verb   URI Pattern                              Controller#Action
#           root GET    /                                        home#index
#         signup GET    /signup(.:format)                        users#new
#        profile GET    /profile(.:format)                       users#show
#     user_posts GET    /users/:user_id/posts(.:format)          posts#index {:exept=>[:index]}
#                POST   /users/:user_id/posts(.:format)          posts#create {:exept=>[:index]}
#  new_user_post GET    /users/:user_id/posts/new(.:format)      posts#new {:exept=>[:index]}
# edit_user_post GET    /users/:user_id/posts/:id/edit(.:format) posts#edit {:exept=>[:index]}
#      user_post GET    /users/:user_id/posts/:id(.:format)      posts#show {:exept=>[:index]}
#                PATCH  /users/:user_id/posts/:id(.:format)      posts#update {:exept=>[:index]}
#                PUT    /users/:user_id/posts/:id(.:format)      posts#update {:exept=>[:index]}
#                DELETE /users/:user_id/posts/:id(.:format)      posts#destroy {:exept=>[:index]}
#          users GET    /users(.:format)                         users#index
#                POST   /users(.:format)                         users#create
#      edit_user GET    /users/:id/edit(.:format)                users#edit
#           user PATCH  /users/:id(.:format)                     users#update
#                PUT    /users/:id(.:format)                     users#update
#                DELETE /users/:id(.:format)                     users#destroy
#          login GET    /login(.:format)                         sessions#new
#         logout GET    /logout(.:format)                        sessions#destroy
#       sessions POST   /sessions(.:format)                      sessions#create
#           city GET    /cities/:short_name(.:format)            cities#show

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :city
  validates :title, length: {minimum: 1, maximum: 200, too_long: "Max 200 characters", too_short: "Minimum 1 character"}
  validates :body, presence: true

  has_attached_file :photo,
                   :styles => { :medium => "700x700>", :small =>"400x400>" },
                   :default_url => 'http://thecatapi.com/api/images/get?format=src&size=small',
                   :escape_url => false,
                   :storage => :s3,
                   :s3_credentials => Proc.new { |a| a.instance.s3_credentials },
                   :s3_host_name => 's3-us-west-1.amazonaws.com'

  def s3_credentials
   { :bucket => ENV['S3_BUCKET'], :access_key_id => ENV['S3_PUBLIC_KEY'], :secret_access_key => ENV['S3_SECRET'] }
  end

  validates_attachment :photo,
                      :content_type => { :content_type => ["image/jpeg", "image/png"] },
                      :size => { :in => 0..4200.kilobytes }

  extend FriendlyId
    friendly_id :title, use: [:slugged, :finders]
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authorize, only: [:delete, :update]

	def create
		user = current_user
		post = current_user.posts.new(post_params)

		if post.save
			redirect_to city_path(post.city.short_name)
		else
			redirect_to new_user_post_path(user)
		end
	end

	def new
		if params[:short_name]
			@city = City.find_by(short_name: params[:short_name])
		else
			@city = City.find(1)
		end
		
		@user = current_user
		@post = Post.new
		render :new
	end

	def edit
		@user = current_user
		@post = Post.find(params[:id])
		render :edit
	end

	def show
		@user = current_user
		@post = Post.find(params[:id])
		render :show
	end

	def update
		@user = current_user
		@post = Post.find(params[:id])

		if current_user.id == @post.user_id
			@post.update_attributes(post_params)
			redirect_to profile_path
		else
			redirect_to root_path
		end
	end

	def destroy
		@user = current_user
		Post.find(params[:id]).destroy
		redirect_to session.delete(:return_to)
	end

	private
	def post_params
		params.require(:post).permit(:title, :body, :city_id, :photo)
	end

end

#     user_posts GET    /users/:user_id/posts(.:format)          posts#index
#                POST   /users/:user_id/posts(.:format)          posts#create
#  new_user_post GET    /users/:user_id/posts/new(.:format)      posts#new
# edit_user_post GET    /users/:user_id/posts/:id/edit(.:format) posts#edit
#      user_post GET    /users/:user_id/posts/:id(.:format)      posts#show
#                PATCH  /users/:user_id/posts/:id(.:format)      posts#update
#                PUT    /users/:user_id/posts/:id(.:format)      posts#update
#                DELETE /users/:user_id/posts/:id(.:format)      posts#destroy

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="col-md-12">
	<div class="col-md-4"></div>
	<div class="col-md-4 post post-border animated slideInLeft">
		<h3>Edit your post</h3>
		<div class="form-group">
			<%= form_for :post, url: user_post_path, method: :put do |f| %>
			<%= f.text_field :title, placeholder: @post.title, class: "form-control" %><br>
			<%= f.text_field :body, placeholder: @post.body, class: "form-control" %><br>
			<%= f.submit "Edit Post" %>
			<% end %>
		</div>
	</div>
	<div class="col-md-4"></div>
</div>

app/views/posts/new.html.erb
<div class="col-md-12">
	<div class="col-md-4"></div>
	<div class="col-md-4 post post-border animated slideInUp">
		<div class="form-group">
			<h3>Create a post</h3>
			<%= form_for :post, url: user_posts_path, :html => { :multipart => true } do |f| %>
			<%= f.text_field :title, placeholder: "Title", class: "form-control" %><br>
			<%= f.text_field :body, placeholder: "body", class: "form-control" %><br>
			<%= f.collection_select :city_id, City.all, :id, :city_name, prompt: true, :selected => @city.id, :class => "btn btn-default dropdown-toggle post-btn" %><br>
			<%= f.file_field :photo %><br>
			<%= f.submit "Save Post" %>
			<% end %>
		</div>
	</div>
	<div class="col-md-4"></div>
</div>

app/views/posts/show.html.erb
<div class="col-md-12">
	<div class="col-md-4"></div>
	<div class="col-md-4 post post-border">
		<div class="form-group">
			<%= image_tag @post.photo.url(:small), class: "center-block" %>
			<h3><%= @post.title %></h3><br>
			<%= @post.created_at.strftime("%b. %Y") %><br>
			<%= @post.body %><br>
			<%= User.find(@post.user_id).username %><br>
			<%= City.find(@post.city_id).city_name %><br>
			<hr class="style-one">
			<% if current_user && (current_user.id == @post.user_id) %>
				<%= link_to "All my posts", profile_path%>
			<% else %>
				<%= link_to "Go back", :back %>
			<% end %>
		</div>
	</div>
	<div class="col-md-4"></div>
</div>