config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  #signup routes
  get "/signup", to: "users#new"
  get "/profile", to: "users#show"
  resources :users, except: [:new, :show], path: "/profile" do 
    resources :posts, exept: [:index]
  end

  #session routes
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  resources :sessions, only: [:create]
  #other shit

  resources :cities, only: [:show], param: :short_name

end

#         Prefix Verb   URI Pattern                              Controller#Action
#           root GET    /                                        home#index
#         signup GET    /signup(.:format)                        users#new
#        profile GET    /profile(.:format)                       users#show
#     user_posts GET    /users/:user_id/posts(.:format)          posts#index {:exept=>[:index]}
#                POST   /users/:user_id/posts(.:format)          posts#create {:exept=>[:index]}
#  new_user_post GET    /users/:user_id/posts/new(.:format)      posts#new {:exept=>[:index]}
# edit_user_post GET    /users/:user_id/posts/:id/edit(.:format) posts#edit {:exept=>[:index]}
#      user_post GET    /users/:user_id/posts/:id(.:format)      posts#show {:exept=>[:index]}
#                PATCH  /users/:user_id/posts/:id(.:format)      posts#update {:exept=>[:index]}
#                PUT    /users/:user_id/posts/:id(.:format)      posts#update {:exept=>[:index]}
#                DELETE /users/:user_id/posts/:id(.:format)      posts#destroy {:exept=>[:index]}
#          users GET    /users(.:format)                         users#index
#                POST   /users(.:format)                         users#create
#      edit_user GET    /users/:id/edit(.:format)                users#edit
#           user PATCH  /users/:id(.:format)                     users#update
#                PUT    /users/:id(.:format)                     users#update
#                DELETE /users/:id(.:format)                     users#destroy
#          login GET    /login(.:format)                         sessions#new
#         logout GET    /logout(.:format)                        sessions#destroy
#       sessions POST   /sessions(.:format)                      sessions#create
#           city GET    /cities/:short_name(.:format)            cities#show

app/models/city.rb
class City < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	def to_param
	  "#{short_name}"
	end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
  	@user = current_user
  	@city = City.find_by(short_name:params[:short_name])
  	session[:return_to] = city_path(@city)

  	@posts = @city.posts.order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/show.html.erb
<div class="col-md-12 map-container animated slideInDown">
	<img class="city-img" src="<%= @city.city_photo %>"></img>
</div>
<div class="col-md-12 post">
	<div class="col-md-3 post-border animated slideInLeft">
		<h1 class="logo"><%= @city.city_name %></h1>
		<hr class="style-one">
		<p><%= @city.city_description %> </p>
		<div>
		<hr class="style-one">	
			<% if current_user %>
			<%= link_to "Write a Post", new_user_post_path(@user, short_name: params[:short_name]), class: "btn btn-default" %>
			<% else %>
			<a href="/login" class="btn btn-default">Log in to write a post</a>
			<% end %>
		</div>
	</div>
	<div class="col-md-1"></div>
	<div class="col-md-7 post-border animated slideInUp">
		<h1>Recent Posts</h1>
		<span><%= paginate @posts %></span>
		<hr class="style-one">
		<div class="title">
			<% @posts.each do |p| %>
			<p>	
				<%= link_to p.title, user_post_path(p.user, p) %>
				<% if current_user && (current_user.id == p.user_id) %>
				<%= link_to "", user_post_path(p.user, p), method: :delete, data: {confirm: "Are you sure?"}, class: "glyphicon glyphicon-remove delete-post" %>
				<%= link_to "", edit_user_post_path(p.user, p), class: "glyphicon glyphicon-pencil" %>	
				<% end %>
			</p>
			<% end %>
		</div>
	</div>
	<div class="col-md-1"></div>
</div>